# Generated by Django 4.2.2 on 2023-07-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False)),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(default='M', max_length=1)),
                ('age', models.IntegerField(max_length=2)),
                ('email', models.EmailField(default='@gmail.com', max_length=254)),
                ('tel', models.CharField(default='06...', max_length=22)),
            ],
        ),
    ]
