# Generated by Django 4.2.2 on 2023-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='age',
            field=models.IntegerField(default='12'),
        ),
    ]
