# Generated by Django 4.2.2 on 2023-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_etudiant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='tel',
            field=models.CharField(default='+24206...', max_length=22),
        ),
    ]
